services:
  transfer_db:
    container_name: transfer_db
    image: postgres:15-alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: transfer
    ports:
      - "5432:5432"